title: I'm TÃ¡o Äá»
description: A sleepy pig
baseurl: "" # the subpath of your site, e.g. /blog
url: "taodo2512.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    TÃ¡o Äá»
author-image:   tao_do_1.jpg
author-job:     Media Freelancer
author-email:   nguyenmaidan2512@gmail.com
author-twitter: maingocchamhoc # Add your twitter account
about-author:   |
        .......................... a dreamy girl ğŸ ........................
        ........................ enjoys studying ğŸ“š ......................
        ..................... capturing moments ğŸ“¸ .................. 
        ........... and writing miscellaneous things ğŸ“ .....

# Social settings
social-twitter:   maingocchamhoc
social-facebook:  profile.php?id=61550288743410    
social-pinterest: Taodo2512
social-instagram: taodo_2512
social-youtube:   playlist?list=PLxkjb2HuBoqVXBOTyHpT42Od5tiQn3Gsh
social-linkedin:  maingocnghiemthi

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: taodo2512 # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
